url: '' # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '' # the subpath of your site, e.g. /blog
title: 'Shubham S. Shah' # the name of your site, e.g. ACME Corp.
sass:
  style: compressed
collections:
  projects:
    permalink: '/:collection/:name/'
    output: true
  contributions:
    permalink: '/:collection/:name/'
    output: true
  blog:
    permalink: '/:collection/:name/'
    output: true
plugins:
  - jemoji
